CREATE TABLE USERS (ID INTEGER NOT NULL, 
"NAME" VARCHAR(50) NOT NULL,
"RATING" NUMERIC(15,3),
"ACTIVE" SMALLINT NOT NULL);


ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (ID);

CREATE GENERATOR USERS_ID_GEN;

SET TERM ^ ;

CREATE TRIGGER USERS_ID_BI FOR USERS
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(USERS_ID_GEN, 1);
END^

SET TERM ; ^
