CREATE TABLE USERS (ID INTEGER NOT NULL, 
"NAME" VARCHAR(50) NOT NULL,
"WEIGHT" DOUBLE PRECISION NOT NULL,
"RATING" NUMERIC(15,3) NOT NULL,
"ACTIVE" SMALLINT NOT NULL,
"DDATE" TIMESTAMP NOT NULL,
"DDAY" DATE NOT NULL,
"LAST_RATING" NUMERIC(15,3));


ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (ID);

CREATE GENERATOR USERS_ID_GEN;

SET TERM ^ ;

CREATE TRIGGER USERS_ID_BI FOR USERS
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(USERS_ID_GEN, 1);
END^

SET TERM ; ^
